title: "CCDC Bible"
author: "CCDC Team Blood, Sweat, and Tears"
geometry:
  - margin=1in
classoption:
  - titlepage
mainfont: "Noto Serif"
sansfont: "Noto Sans"
monofont: "Noto Sans Mono"
header-includes:
  - \input{preamble.tex}