name: Build PDFs (presets)

on:
  workflow_dispatch:
    inputs:
      build_all:
        description: "Build all presets (if false, build only 'preset')"
        type: boolean
        required: true
        default: true
      preset:
        description: "Preset name to build when build_all=false"
        required: false
        default: ""

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    container: 
      image: pandoc/latex:latest

    strategy:
      fail-fast: false
      matrix:
        include:
          # ↓ Define your presets here
          - name: first30
            keep: '[".first30"]'
          - name: general-linux
            keep: '[".general#linux"]'
          - name: general-windows
            keep: '[".general#windows"]'
          - name: os-info
            keep: '[".os"]'
          
    steps:
      - uses: actions/checkout@v4

      - name: Get version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          dry_run: true
      - run:
          TAG=${{ steps.tag.outputs.previous_tag }}

      - name: Install fonts
        run: |
          apk add --no-cache fontconfig font-noto
          fc-cache -fv

      - name: Setup Buildinfo
        run : |
          DATE="$(date -u '+%m-%d-%Y')"
          echo "\renewcommand{\version}{\texttt{\detokenize{$${{ steps.tag.outputs.previous_tag }}}}}" >> build/buildinfo.tex
          echo "\renewcommand{\builddate}{$DATE}" >> build/buildinfo.tex

      # Skip presets if build_all=false and this isn't the chosen one
      - name: Build preset
        if: ${{ inputs.build_all || matrix.name == inputs.preset }}
        env:
          NAME:      ${{ matrix.name }}
          KEEP:      ${{ matrix.keep }}
        run: |
          set -euo pipefail

          FILTER='--lua-filter=filters/extract-sections.lua'

          echo "Preset: ${NAME}"
          echo "Keep  : ${KEEP}"

          pandoc ccdc-bible.md \
            --metadata-file=build/meta.yaml \
            --include-in-header=build/preamble.tex \
            --include-in-header=build/buildinfo.tex \
            --toc \
            -o "./${NAME}-${{ steps.tag.outputs.previous_tag }}.pdf" \
            --pdf-engine="xelatex" \
            $FILTER -M keep="${KEEP}" \
            --lua-filter=build/h2-pagebreak.lua

      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: pdfs
          path: ./*.pdf
